name: Android firebase app distribution

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: set up pre-deploy configurations
        run: |
          chmod +x ./.github/scripts/pre-deploy.sh
          ./.github/scripts/pre-deploy.sh
      - name: build release
        run: ./gradlew test assembleRelease --stacktrace
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFile: app/google-services.json
          file: app/build/outputs/apk/release/app-release-google.apk
          groups: early-access-supporters
